### PR TITLE
Update to submodules

### PR DESCRIPTION
**Pull request by mlarocque-oti**
Need to first merge the PR in the submodules.

### CODE REVIEW

**Review by jmuncaster — CHANGES_REQUESTED** [review]
Sub modules merged, please update to main. Thanks for the contribution!!!

**Comment by mlarocque-oti** [comment]
Thanks!
Submodules updated; but please wait before merging this one, as I still have a problem on a specific platform. It may or may not be related to this module...

**Comment by mlarocque-oti** [comment]
Now all tests are passing for my app. Also tested building on Ubuntu 20.04 with success.
Ready to merge!

**Review by jmuncaster — APPROVED** [review]

**Comment by jmuncaster** [comment]
Thanks!!

**Pull request merged**
